---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "thanos-receive.labels" . | nindent 4 }}
    app.kubernetes.io/component: thanos-receive
  name: {{ include "thanos-receive.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: http
    name: http
  - port: 19891
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector: {{- include "thanos-receive.selectorLabels" . | nindent 4 }}
  type: ClusterIP
